---
- name: Network Configuration
  hosts: all
  gather_facts: no
  tasks:
    - name: Configure Router Interfaces
      ios_config:
        lines:
          - interface GigabitEthernet0/0
          - ip address 192.168.1.1 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet0/0
      when: inventory_hostname == "R1"

    - name: Configure Router Interfaces
      ios_config:
        lines:
          - interface GigabitEthernet0/1
          - ip address 192.168.2.1 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet0/1
      when: inventory_hostname == "R2"

    - name: Configure Router Interfaces
      ios_config:
        lines:
          - interface GigabitEthernet0/1
          - ip address 192.168.3.1 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet0/1
      when: inventory_hostname == "R3"

    - name: Configure Router Interfaces
      ios_config:
        lines:
          - interface GigabitEthernet0/0
          - ip address 192.168.4.1 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet0/0
      when: inventory_hostname == "R4"
